export interface District {
  id: string;
  name: string;         // Moldovan Cyrillic
  nameRo: string;       // Romanian
  nameRu: string;       // Russian
  capital: string;      // capital city in Cyrillic
  capitalRo: string;
  population: number;
  area: number;         // km²
  coat: string;         // emoji placeholder
  description: string;  // Cyrillic
  color: string;
  cx: number;           // SVG center X
  cy: number;           // SVG center Y
}

export const DISTRICTS: District[] = [
  {
    id: "briceni",
    name: "Бричень",
    nameRo: "Briceni",
    nameRu: "Бричень",
    capital: "Бричень",
    capitalRo: "Briceni",
    population: 73600,
    area: 812,
    coat: "🏛️",
    description: "Район ын нордул Молдовей, ла граница ку Украина ши Ромыния.",
    color: "#3b6e8f",
    cx: 95, cy: 55
  },
  {
    id: "ocnita",
    name: "Окница",
    nameRo: "Ocnița",
    nameRu: "Окница",
    capital: "Окница",
    capitalRo: "Ocnița",
    population: 55500,
    area: 591,
    coat: "⛏️",
    description: "Район ын норд-вест, кунескут пентру минеле де салт.",
    color: "#2d5a7b",
    cx: 130, cy: 60
  },
  {
    id: "soroca",
    name: "Сорока",
    nameRo: "Soroca",
    nameRu: "Сорока",
    capital: "Сорока",
    capitalRo: "Soroca",
    population: 95700,
    area: 1346,
    coat: "🏰",
    description: "Район ку челебра Четате а Сорочий, констruit де Штефан чел Маре.",
    color: "#1e6b5e",
    cx: 175, cy: 75
  },
  {
    id: "donduseni",
    name: "Дондушень",
    nameRo: "Dondușeni",
    nameRu: "Дондушень",
    capital: "Дондушень",
    capitalRo: "Dondușeni",
    population: 44800,
    area: 645,
    coat: "🌾",
    description: "Район аграр ын нордул Молдовей.",
    color: "#4a7c59",
    cx: 145, cy: 90
  },
  {
    id: "floresti",
    name: "Флорешть",
    nameRo: "Florești",
    nameRu: "Флорешть",
    capital: "Флорешть",
    capitalRo: "Florești",
    population: 86500,
    area: 1316,
    coat: "🌸",
    description: "Район кунескут пентру ливезиле де мере ши вий.",
    color: "#5c8a3c",
    cx: 150, cy: 120
  },
  {
    id: "rezina",
    name: "Резина",
    nameRo: "Rezina",
    nameRu: "Резина",
    capital: "Резина",
    capitalRo: "Rezina",
    population: 49700,
    area: 896,
    coat: "⛪",
    description: "Район пе малул Ниструлуй ку векиле мэнэстирь.",
    color: "#4e7a6d",
    cx: 185, cy: 140
  },
  {
    id: "drochia",
    name: "Дрокия",
    nameRo: "Drochia",
    nameRu: "Дрокия",
    capital: "Дрокия",
    capitalRo: "Drochia",
    population: 87200,
    area: 1248,
    coat: "🌻",
    description: "Район аграр ын нордул централ ал Молдовей.",
    color: "#6b8c2e",
    cx: 120, cy: 110
  },
  {
    id: "singerei",
    name: "Сынджерей",
    nameRo: "Sîngerei",
    nameRu: "Сынджерей",
    capital: "Сынджерей",
    capitalRo: "Sîngerei",
    population: 88600,
    area: 1437,
    coat: "🍇",
    description: "Район виникол ын центрул норд ал Молдовей.",
    color: "#7a5c8a",
    cx: 130, cy: 145
  },
  {
    id: "balti",
    name: "Бэлць",
    nameRo: "Bălți",
    nameRu: "Бельцы",
    capital: "Бэлць",
    capitalRo: "Bălți",
    population: 102200,
    area: 78,
    coat: "🏙️",
    description: "Ал доиля ораш ка мэриме дин Молдова, центрул норд ал цэрий.",
    color: "#8b4513",
    cx: 110, cy: 130
  },
  {
    id: "riscani",
    name: "Рышкань",
    nameRo: "Rîșcani",
    nameRu: "Рышкань",
    capital: "Рышкань",
    capitalRo: "Rîșcani",
    population: 67500,
    area: 945,
    coat: "🌿",
    description: "Район аграр ын норд-вестул Молдовей.",
    color: "#5c7a3c",
    cx: 90, cy: 140
  },
  {
    id: "glodeni",
    name: "Глодень",
    nameRo: "Glodeni",
    nameRu: "Глодень",
    capital: "Глодень",
    capitalRo: "Glodeni",
    population: 60200,
    area: 756,
    coat: "🌱",
    description: "Район аграр ла вест де Бэлць.",
    color: "#4a8c4a",
    cx: 90, cy: 165
  },
  {
    id: "falesti",
    name: "Фэлешть",
    nameRo: "Fălești",
    nameRu: "Фалешты",
    capital: "Фэлешть",
    capitalRo: "Fălești",
    population: 89300,
    area: 1076,
    coat: "🐄",
    description: "Район ку традиций ын зоотехние ши агрикултурэ.",
    color: "#6b8c4a",
    cx: 95, cy: 190
  },
  {
    id: "ungheni",
    name: "Унгень",
    nameRo: "Ungheni",
    nameRu: "Унгень",
    capital: "Унгень",
    capitalRo: "Ungheni",
    population: 112200,
    area: 1068,
    coat: "🌉",
    description: "Порт де интраре дин Ромыния, ку под песте рыул Прут.",
    color: "#3a7a6e",
    cx: 85, cy: 210
  },
  {
    id: "nisporeni",
    name: "Ниспорень",
    nameRo: "Nisporeni",
    nameRu: "Ниспорень",
    capital: "Ниспорень",
    capitalRo: "Nisporeni",
    population: 65700,
    area: 643,
    coat: "🍎",
    description: "Район виникол ши помикол ын вест-чентралул Молдовей.",
    color: "#5c8a5c",
    cx: 100, cy: 230
  },
  {
    id: "telenesti",
    name: "Теленешть",
    nameRo: "Telenești",
    nameRu: "Теленешть",
    capital: "Теленешть",
    capitalRo: "Telenești",
    population: 73100,
    area: 846,
    coat: "🌄",
    description: "Район ын чентрул Молдовей, ку пейзаже питорешть.",
    color: "#6b7a4a",
    cx: 145, cy: 175
  },
  {
    id: "orhei",
    name: "Орхей",
    nameRo: "Orhei",
    nameRu: "Оргеев",
    capital: "Орхей",
    capitalRo: "Orhei",
    population: 120000,
    area: 1452,
    coat: "🏛️",
    description: "Район ку векиул Орхей, ун ситус аркеолоӂик уник.",
    color: "#4a6b8c",
    cx: 160, cy: 200
  },
  {
    id: "chisinau",
    name: "Кишинэу",
    nameRo: "Chișinău",
    nameRu: "Кишинёв",
    capital: "Кишинэу",
    capitalRo: "Chișinău",
    population: 684600,
    area: 573,
    coat: "🏛️",
    description: "Капитала Републичий Молдова, чел май маре ораш дин царэ.",
    color: "#8b1a1a",
    cx: 150, cy: 235
  },
  {
    id: "straseni",
    name: "Стрэшень",
    nameRo: "Strășeni",
    nameRu: "Страшены",
    capital: "Стрэшень",
    capitalRo: "Strășeni",
    population: 89500,
    area: 723,
    coat: "🌲",
    description: "Район пэдурос ын чентрул Молдовей, апроапе де Кишинэу.",
    color: "#2d6b3a",
    cx: 125, cy: 245
  },
  {
    id: "ialoveni",
    name: "Яловень",
    nameRo: "Ialoveni",
    nameRu: "Яловены",
    capital: "Яловень",
    capitalRo: "Ialoveni",
    population: 98700,
    area: 782,
    coat: "🍷",
    description: "Район виникол ла суд де Кишинэу.",
    color: "#6b2d5c",
    cx: 140, cy: 265
  },
  {
    id: "calarasi",
    name: "Кэлэрашь",
    nameRo: "Călărași",
    nameRu: "Каларашь",
    capital: "Кэлэрашь",
    capitalRo: "Călărași",
    population: 75200,
    area: 897,
    coat: "🐎",
    description: "Район ку традиций ын крештерял кайлор.",
    color: "#7a5c2d",
    cx: 110, cy: 265
  },
  {
    id: "hincesti",
    name: "Хынчешть",
    nameRo: "Hîncești",
    nameRu: "Хынчешть",
    capital: "Хынчешть",
    capitalRo: "Hîncești",
    population: 119900,
    area: 1413,
    coat: "🌳",
    description: "Унул дин чел май марь районе дин Молдова, ла суд-вест де Кишинэу.",
    color: "#4a7a3a",
    cx: 120, cy: 290
  },
  {
    id: "anenii_noi",
    name: "Аненийй Ной",
    nameRo: "Anenii Noi",
    nameRu: "Новые Аненьт",
    capital: "Аненийй Ной",
    capitalRo: "Anenii Noi",
    population: 81800,
    area: 797,
    coat: "🌊",
    description: "Район пе малул стынг ал Ниструлуй.",
    color: "#2d6b7a",
    cx: 175, cy: 265
  },
  {
    id: "criuleni",
    name: "Криулень",
    nameRo: "Criuleni",
    nameRu: "Криулень",
    capital: "Криулень",
    capitalRo: "Criuleni",
    population: 72500,
    area: 661,
    coat: "🌾",
    description: "Район пе ры̃ул Быч, ла ест де Кишинэу.",
    color: "#5c8a2d",
    cx: 185, cy: 240
  },
  {
    id: "dubasari",
    name: "Дубэсарь",
    nameRo: "Dubăsari",
    nameRu: "Дубоссары",
    capital: "Дубэсарь",
    capitalRo: "Dubăsari",
    population: 34100,
    area: 528,
    coat: "💧",
    description: "Район пе Нистру, ку лакул де акумуларе Дубэсарь.",
    color: "#1a5c7a",
    cx: 200, cy: 210
  },
  {
    id: "soldanesti",
    name: "Шолдэнешть",
    nameRo: "Șoldănești",
    nameRu: "Шолданешты",
    capital: "Шолдэнешть",
    capitalRo: "Șoldănești",
    population: 43300,
    area: 646,
    coat: "🦅",
    description: "Район ын ест-чентрул Молдовей.",
    color: "#3a6b5c",
    cx: 195, cy: 170
  },
  {
    id: "causeni",
    name: "Кэушень",
    nameRo: "Căușeni",
    nameRu: "Каушаны",
    capital: "Кэушень",
    capitalRo: "Căușeni",
    population: 91800,
    area: 1246,
    coat: "🏺",
    description: "Район ку весть ситусурь аркеолоӂиче дин периоада Гетикэ.",
    color: "#6b4a2d",
    cx: 195, cy: 290
  },
  {
    id: "stefan_voda",
    name: "Штефан Водэ",
    nameRo: "Ștefan Vodă",
    nameRu: "Штефан-Водэ",
    capital: "Штефан Водэ",
    capitalRo: "Ștefan Vodă",
    population: 70900,
    area: 1078,
    coat: "⚔️",
    description: "Район нумит дупэ Штефан чел Маре, Домнул Молдовей.",
    color: "#7a1a1a",
    cx: 205, cy: 320
  },
  {
    id: "basarabeasca",
    name: "Басарабяска",
    nameRo: "Basarabeasca",
    nameRu: "Басарабяска",
    capital: "Басарабяска",
    capitalRo: "Basarabeasca",
    population: 28300,
    area: 477,
    coat: "🚂",
    description: "Чел май мик район дин Молдова, кунескут пентру ноддул феровяр.",
    color: "#5c3a6b",
    cx: 165, cy: 320
  },
  {
    id: "cimislia",
    name: "Чимишлия",
    nameRo: "Cimișlia",
    nameRu: "Чимишлия",
    capital: "Чимишлия",
    capitalRo: "Cimișlia",
    population: 61700,
    area: 1163,
    coat: "☀️",
    description: "Район ла суд-вест, кунескут пентру климатул кэлдурос ши вий.",
    color: "#8c6b2d",
    cx: 140, cy: 320
  },
  {
    id: "leova",
    name: "Леова",
    nameRo: "Leova",
    nameRu: "Леово",
    capital: "Леова",
    capitalRo: "Leova",
    population: 51900,
    area: 834,
    coat: "🌿",
    description: "Район пе малул Прутулуй ла суд-вест Молдовей.",
    color: "#3a7a3a",
    cx: 110, cy: 320
  },
  {
    id: "cantemir",
    name: "Кантемир",
    nameRo: "Cantemir",
    nameRu: "Кантемир",
    capital: "Кантемир",
    capitalRo: "Cantemir",
    population: 60100,
    area: 882,
    coat: "📜",
    description: "Район нумит дупэ Димитрие Кантемир, марелe ынвэцат молдовян.",
    color: "#4a5c7a",
    cx: 120, cy: 345
  },
  {
    id: "taraclia",
    name: "Тарачия",
    nameRo: "Taraclia",
    nameRu: "Тараклия",
    capital: "Тарачия",
    capitalRo: "Taraclia",
    population: 43200,
    area: 663,
    coat: "🌺",
    description: "Район ку популацие булгарэ семнификативэ ын судул Молдовей.",
    color: "#6b3a5c",
    cx: 170, cy: 355
  },
  {
    id: "cahul",
    name: "Кахул",
    nameRo: "Cahul",
    nameRu: "Кагул",
    capital: "Кахул",
    capitalRo: "Cahul",
    population: 120600,
    area: 1551,
    coat: "🌊",
    description: "Чел май маре район дин суд, ла конфлуенца Прутулуй ку Дунэря.",
    color: "#1a6b8c",
    cx: 130, cy: 370
  },
];

export const TOTAL_POPULATION = DISTRICTS.reduce((s, d) => s + d.population, 0);
export const TOTAL_AREA = DISTRICTS.reduce((s, d) => s + d.area, 0);
